[package]
name = "strided-perm"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "Cache-efficient tensor permutation / transpose (HPTT-inspired)."

[dependencies]
strided-view.workspace = true
rayon = { workspace = true, optional = true }

[features]
parallel = ["dep:rayon"]

[dev-dependencies]
criterion.workspace = true
rand.workspace = true
rand_distr.workspace = true
rayon.workspace = true

[lib]
bench = false

[[bench]]
name = "permute"
harness = false
